title: "CHS Engineering Club"
description: "CHS Engineering Roles"

theme: minima

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

# Minima theme customization
minima:
  skin: dark # Choose 'dark', 'light', or 'default' as your color scheme

# Social Links
social_links: "" #add social media later
  github: 

